name: ecommerce_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  animated_custom_dropdown: ^3.1.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  drop_down_search_field: ^1.2.2
  dropdown_search: ^6.0.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.11.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1


dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/